defaults:
  - hydra: custom
  - data_path: theta

description: 'Validation'

bs: 32
desired_bs: 32
device: cuda:2
path: null
ckpt: null

metrics:
  - type: metrics.Recall
  - type: metrics.Precision
  - type: metrics.AveragePrecision
  - type: metrics.IoU

validation_dataset:
  - ${megapixel_mnist_val_novel_cats}
  - ${megapixel_mnist_val_train_cats}